// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizdS-87upVIbnmSrCrYS3SOybWV4z2aE',
    appId: '1:980297382859:web:0fadfe87629d34cf55544e',
    messagingSenderId: '980297382859',
    projectId: 'todoapp-5c588',
    authDomain: 'todoapp-5c588.firebaseapp.com',
    storageBucket: 'todoapp-5c588.firebasestorage.app',
    measurementId: 'G-351FJ58CCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpuWYWrcYID4uLN1Z3z0ZzOuegp6EpaX4',
    appId: '1:980297382859:android:6dcce635f153eeae55544e',
    messagingSenderId: '980297382859',
    projectId: 'todoapp-5c588',
    storageBucket: 'todoapp-5c588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1TQKUrIPzKWkDs1Rr16hk4KOh8w6HbTM',
    appId: '1:980297382859:ios:1d0429bd4f6c84fc55544e',
    messagingSenderId: '980297382859',
    projectId: 'todoapp-5c588',
    storageBucket: 'todoapp-5c588.firebasestorage.app',
    iosBundleId: 'com.example.totoAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1TQKUrIPzKWkDs1Rr16hk4KOh8w6HbTM',
    appId: '1:980297382859:ios:1d0429bd4f6c84fc55544e',
    messagingSenderId: '980297382859',
    projectId: 'todoapp-5c588',
    storageBucket: 'todoapp-5c588.firebasestorage.app',
    iosBundleId: 'com.example.totoAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBizdS-87upVIbnmSrCrYS3SOybWV4z2aE',
    appId: '1:980297382859:web:4034b5098d228dbd55544e',
    messagingSenderId: '980297382859',
    projectId: 'todoapp-5c588',
    authDomain: 'todoapp-5c588.firebaseapp.com',
    storageBucket: 'todoapp-5c588.firebasestorage.app',
    measurementId: 'G-R1E45KQMQD',
  );
}
